CREATE DATABASE CUSTOMER_INFO

--\c customer_info

create table PARTY_DETAILS(
	PARTY_ID SERIAL UNIQUE PRIMARY KEY  NOT NULL,
	PARTY_NAME TEXT NOT NULL,
    PARTY_ADDRESS TEXT NOT NULL,
	PARTY_SEX TEXT,
	PARTY_AGE INT NOT NULL,
	PARTY_MAIL TEXT NOT NULL,
	PARTY_PHONE INT
);

